// Generated by gencpp from file r_chatbot/EmotionRecognizeResponse.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_EMOTIONRECOGNIZERESPONSE_H
#define R_CHATBOT_MESSAGE_EMOTIONRECOGNIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r_chatbot
{
template <class ContainerAllocator>
struct EmotionRecognizeResponse_
{
  typedef EmotionRecognizeResponse_<ContainerAllocator> Type;

  EmotionRecognizeResponse_()
    : emotion()  {
    }
  EmotionRecognizeResponse_(const ContainerAllocator& _alloc)
    : emotion(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _emotion_type;
  _emotion_type emotion;




  typedef boost::shared_ptr< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionRecognizeResponse_

typedef ::r_chatbot::EmotionRecognizeResponse_<std::allocator<void> > EmotionRecognizeResponse;

typedef boost::shared_ptr< ::r_chatbot::EmotionRecognizeResponse > EmotionRecognizeResponsePtr;
typedef boost::shared_ptr< ::r_chatbot::EmotionRecognizeResponse const> EmotionRecognizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r_chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'r_chatbot': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/r_chatbot/msg'], 'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "320a4a5f8df4421af3ae0d4c52f87ab8";
  }

  static const char* value(const ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x320a4a5f8df4421aULL;
  static const uint64_t static_value2 = 0xf3ae0d4c52f87ab8ULL;
};

template<class ContainerAllocator>
struct DataType< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r_chatbot/EmotionRecognizeResponse";
  }

  static const char* value(const ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string emotion\n\
\n\
";
  }

  static const char* value(const ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionRecognizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r_chatbot::EmotionRecognizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "emotion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.emotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R_CHATBOT_MESSAGE_EMOTIONRECOGNIZERESPONSE_H
