// Generated by gencpp from file r_chatbot/FaceRecognize.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_FACERECOGNIZE_H
#define R_CHATBOT_MESSAGE_FACERECOGNIZE_H

#include <ros/service_traits.h>


#include <r_chatbot/FaceRecognizeRequest.h>
#include <r_chatbot/FaceRecognizeResponse.h>


namespace r_chatbot
{

struct FaceRecognize
{

typedef FaceRecognizeRequest Request;
typedef FaceRecognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceRecognize
} // namespace r_chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r_chatbot::FaceRecognize > {
  static const char* value()
  {
    return "8c4e0d5dbd11845ff7ce7f7f9a92fb2f";
  }

  static const char* value(const ::r_chatbot::FaceRecognize&) { return value(); }
};

template<>
struct DataType< ::r_chatbot::FaceRecognize > {
  static const char* value()
  {
    return "r_chatbot/FaceRecognize";
  }

  static const char* value(const ::r_chatbot::FaceRecognize&) { return value(); }
};


// service_traits::MD5Sum< ::r_chatbot::FaceRecognizeRequest> should match 
// service_traits::MD5Sum< ::r_chatbot::FaceRecognize > 
template<>
struct MD5Sum< ::r_chatbot::FaceRecognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::r_chatbot::FaceRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::FaceRecognizeRequest> should match 
// service_traits::DataType< ::r_chatbot::FaceRecognize > 
template<>
struct DataType< ::r_chatbot::FaceRecognizeRequest>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::r_chatbot::FaceRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r_chatbot::FaceRecognizeResponse> should match 
// service_traits::MD5Sum< ::r_chatbot::FaceRecognize > 
template<>
struct MD5Sum< ::r_chatbot::FaceRecognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::r_chatbot::FaceRecognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::FaceRecognizeResponse> should match 
// service_traits::DataType< ::r_chatbot::FaceRecognize > 
template<>
struct DataType< ::r_chatbot::FaceRecognizeResponse>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::r_chatbot::FaceRecognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R_CHATBOT_MESSAGE_FACERECOGNIZE_H
