// Generated by gencpp from file r_chatbot/GetTopicsRequest.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_GETTOPICSREQUEST_H
#define R_CHATBOT_MESSAGE_GETTOPICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r_chatbot
{
template <class ContainerAllocator>
struct GetTopicsRequest_
{
  typedef GetTopicsRequest_<ContainerAllocator> Type;

  GetTopicsRequest_()
    : input_sentence()  {
    }
  GetTopicsRequest_(const ContainerAllocator& _alloc)
    : input_sentence(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_sentence_type;
  _input_sentence_type input_sentence;




  typedef boost::shared_ptr< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTopicsRequest_

typedef ::r_chatbot::GetTopicsRequest_<std::allocator<void> > GetTopicsRequest;

typedef boost::shared_ptr< ::r_chatbot::GetTopicsRequest > GetTopicsRequestPtr;
typedef boost::shared_ptr< ::r_chatbot::GetTopicsRequest const> GetTopicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r_chatbot::GetTopicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r_chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d411197e9ca3cd6cbe0715c258cc9f9e";
  }

  static const char* value(const ::r_chatbot::GetTopicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd411197e9ca3cd6cULL;
  static const uint64_t static_value2 = 0xbe0715c258cc9f9eULL;
};

template<class ContainerAllocator>
struct DataType< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r_chatbot/GetTopicsRequest";
  }

  static const char* value(const ::r_chatbot::GetTopicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input_sentence\n\
\n\
";
  }

  static const char* value(const ::r_chatbot::GetTopicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_sentence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTopicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r_chatbot::GetTopicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r_chatbot::GetTopicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_sentence: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input_sentence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R_CHATBOT_MESSAGE_GETTOPICSREQUEST_H
