// Generated by gencpp from file r_chatbot/LoadHistoryResponse.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_LOADHISTORYRESPONSE_H
#define R_CHATBOT_MESSAGE_LOADHISTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r_chatbot
{
template <class ContainerAllocator>
struct LoadHistoryResponse_
{
  typedef LoadHistoryResponse_<ContainerAllocator> Type;

  LoadHistoryResponse_()
    : retval(0)  {
    }
  LoadHistoryResponse_(const ContainerAllocator& _alloc)
    : retval(0)  {
  (void)_alloc;
    }



   typedef int32_t _retval_type;
  _retval_type retval;




  typedef boost::shared_ptr< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadHistoryResponse_

typedef ::r_chatbot::LoadHistoryResponse_<std::allocator<void> > LoadHistoryResponse;

typedef boost::shared_ptr< ::r_chatbot::LoadHistoryResponse > LoadHistoryResponsePtr;
typedef boost::shared_ptr< ::r_chatbot::LoadHistoryResponse const> LoadHistoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r_chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5697a1e05c2a3e1c23cab49a31319ec";
  }

  static const char* value(const ::r_chatbot::LoadHistoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5697a1e05c2a3e1ULL;
  static const uint64_t static_value2 = 0xc23cab49a31319ecULL;
};

template<class ContainerAllocator>
struct DataType< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r_chatbot/LoadHistoryResponse";
  }

  static const char* value(const ::r_chatbot::LoadHistoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 retval\n\
";
  }

  static const char* value(const ::r_chatbot::LoadHistoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.retval);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadHistoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r_chatbot::LoadHistoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r_chatbot::LoadHistoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "retval: ";
    Printer<int32_t>::stream(s, indent + "  ", v.retval);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R_CHATBOT_MESSAGE_LOADHISTORYRESPONSE_H
