(cl:defpackage r_chatbot-srv
  (:use )
  (:export
   "CONTEXT"
   "<CONTEXT-REQUEST>"
   "CONTEXT-REQUEST"
   "<CONTEXT-RESPONSE>"
   "CONTEXT-RESPONSE"
   "EMOTIONRECOGNIZE"
   "<EMOTIONRECOGNIZE-REQUEST>"
   "EMOTIONRECOGNIZE-REQUEST"
   "<EMOTIONRECOGNIZE-RESPONSE>"
   "EMOTIONRECOGNIZE-RESPONSE"
   "FACERECOGNIZE"
   "<FACERECOGNIZE-REQUEST>"
   "FACERECOGNIZE-REQUEST"
   "<FACERECOGNIZE-RESPONSE>"
   "FACERECOGNIZE-RESPONSE"
   "FACETRAIN"
   "<FACETRAIN-REQUEST>"
   "FACETRAIN-REQUEST"
   "<FACETRAIN-RESPONSE>"
   "FACETRAIN-RESPONSE"
  ))

