// Generated by gencpp from file chatbot/EmotionRecognize.msg
// DO NOT EDIT!


#ifndef CHATBOT_MESSAGE_EMOTIONRECOGNIZE_H
#define CHATBOT_MESSAGE_EMOTIONRECOGNIZE_H

#include <ros/service_traits.h>


#include <chatbot/EmotionRecognizeRequest.h>
#include <chatbot/EmotionRecognizeResponse.h>


namespace chatbot
{

struct EmotionRecognize
{

typedef EmotionRecognizeRequest Request;
typedef EmotionRecognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmotionRecognize
} // namespace chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chatbot::EmotionRecognize > {
  static const char* value()
  {
    return "6903c14b3c9a61ea8a677558ebfcc4e5";
  }

  static const char* value(const ::chatbot::EmotionRecognize&) { return value(); }
};

template<>
struct DataType< ::chatbot::EmotionRecognize > {
  static const char* value()
  {
    return "chatbot/EmotionRecognize";
  }

  static const char* value(const ::chatbot::EmotionRecognize&) { return value(); }
};


// service_traits::MD5Sum< ::chatbot::EmotionRecognizeRequest> should match 
// service_traits::MD5Sum< ::chatbot::EmotionRecognize > 
template<>
struct MD5Sum< ::chatbot::EmotionRecognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::chatbot::EmotionRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot::EmotionRecognizeRequest> should match 
// service_traits::DataType< ::chatbot::EmotionRecognize > 
template<>
struct DataType< ::chatbot::EmotionRecognizeRequest>
{
  static const char* value()
  {
    return DataType< ::chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::chatbot::EmotionRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chatbot::EmotionRecognizeResponse> should match 
// service_traits::MD5Sum< ::chatbot::EmotionRecognize > 
template<>
struct MD5Sum< ::chatbot::EmotionRecognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::chatbot::EmotionRecognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot::EmotionRecognizeResponse> should match 
// service_traits::DataType< ::chatbot::EmotionRecognize > 
template<>
struct DataType< ::chatbot::EmotionRecognizeResponse>
{
  static const char* value()
  {
    return DataType< ::chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::chatbot::EmotionRecognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHATBOT_MESSAGE_EMOTIONRECOGNIZE_H
