// Generated by gencpp from file chatbot/FaceRecognize.msg
// DO NOT EDIT!


#ifndef CHATBOT_MESSAGE_FACERECOGNIZE_H
#define CHATBOT_MESSAGE_FACERECOGNIZE_H

#include <ros/service_traits.h>


#include <chatbot/FaceRecognizeRequest.h>
#include <chatbot/FaceRecognizeResponse.h>


namespace chatbot
{

struct FaceRecognize
{

typedef FaceRecognizeRequest Request;
typedef FaceRecognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceRecognize
} // namespace chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chatbot::FaceRecognize > {
  static const char* value()
  {
    return "8c4e0d5dbd11845ff7ce7f7f9a92fb2f";
  }

  static const char* value(const ::chatbot::FaceRecognize&) { return value(); }
};

template<>
struct DataType< ::chatbot::FaceRecognize > {
  static const char* value()
  {
    return "chatbot/FaceRecognize";
  }

  static const char* value(const ::chatbot::FaceRecognize&) { return value(); }
};


// service_traits::MD5Sum< ::chatbot::FaceRecognizeRequest> should match 
// service_traits::MD5Sum< ::chatbot::FaceRecognize > 
template<>
struct MD5Sum< ::chatbot::FaceRecognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::chatbot::FaceRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot::FaceRecognizeRequest> should match 
// service_traits::DataType< ::chatbot::FaceRecognize > 
template<>
struct DataType< ::chatbot::FaceRecognizeRequest>
{
  static const char* value()
  {
    return DataType< ::chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::chatbot::FaceRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chatbot::FaceRecognizeResponse> should match 
// service_traits::MD5Sum< ::chatbot::FaceRecognize > 
template<>
struct MD5Sum< ::chatbot::FaceRecognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::chatbot::FaceRecognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot::FaceRecognizeResponse> should match 
// service_traits::DataType< ::chatbot::FaceRecognize > 
template<>
struct DataType< ::chatbot::FaceRecognizeResponse>
{
  static const char* value()
  {
    return DataType< ::chatbot::FaceRecognize >::value();
  }
  static const char* value(const ::chatbot::FaceRecognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHATBOT_MESSAGE_FACERECOGNIZE_H
