// Generated by gencpp from file chatbot/FaceTrainResponse.msg
// DO NOT EDIT!


#ifndef CHATBOT_MESSAGE_FACETRAINRESPONSE_H
#define CHATBOT_MESSAGE_FACETRAINRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chatbot
{
template <class ContainerAllocator>
struct FaceTrainResponse_
{
  typedef FaceTrainResponse_<ContainerAllocator> Type;

  FaceTrainResponse_()
    : id(0)  {
    }
  FaceTrainResponse_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::chatbot::FaceTrainResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chatbot::FaceTrainResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FaceTrainResponse_

typedef ::chatbot::FaceTrainResponse_<std::allocator<void> > FaceTrainResponse;

typedef boost::shared_ptr< ::chatbot::FaceTrainResponse > FaceTrainResponsePtr;
typedef boost::shared_ptr< ::chatbot::FaceTrainResponse const> FaceTrainResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chatbot::FaceTrainResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chatbot::FaceTrainResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot::FaceTrainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot::FaceTrainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot::FaceTrainResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::chatbot::FaceTrainResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chatbot/FaceTrainResponse";
  }

  static const char* value(const ::chatbot::FaceTrainResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 id\n\
\n\
";
  }

  static const char* value(const ::chatbot::FaceTrainResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceTrainResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chatbot::FaceTrainResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chatbot::FaceTrainResponse_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHATBOT_MESSAGE_FACETRAINRESPONSE_H
