// Generated by gencpp from file chatbot/FaceTrain.msg
// DO NOT EDIT!


#ifndef CHATBOT_MESSAGE_FACETRAIN_H
#define CHATBOT_MESSAGE_FACETRAIN_H

#include <ros/service_traits.h>


#include <chatbot/FaceTrainRequest.h>
#include <chatbot/FaceTrainResponse.h>


namespace chatbot
{

struct FaceTrain
{

typedef FaceTrainRequest Request;
typedef FaceTrainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceTrain
} // namespace chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chatbot::FaceTrain > {
  static const char* value()
  {
    return "b390e99f3af36e07f2b7d5e1bf39f6f2";
  }

  static const char* value(const ::chatbot::FaceTrain&) { return value(); }
};

template<>
struct DataType< ::chatbot::FaceTrain > {
  static const char* value()
  {
    return "chatbot/FaceTrain";
  }

  static const char* value(const ::chatbot::FaceTrain&) { return value(); }
};


// service_traits::MD5Sum< ::chatbot::FaceTrainRequest> should match 
// service_traits::MD5Sum< ::chatbot::FaceTrain > 
template<>
struct MD5Sum< ::chatbot::FaceTrainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot::FaceTrain >::value();
  }
  static const char* value(const ::chatbot::FaceTrainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot::FaceTrainRequest> should match 
// service_traits::DataType< ::chatbot::FaceTrain > 
template<>
struct DataType< ::chatbot::FaceTrainRequest>
{
  static const char* value()
  {
    return DataType< ::chatbot::FaceTrain >::value();
  }
  static const char* value(const ::chatbot::FaceTrainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chatbot::FaceTrainResponse> should match 
// service_traits::MD5Sum< ::chatbot::FaceTrain > 
template<>
struct MD5Sum< ::chatbot::FaceTrainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot::FaceTrain >::value();
  }
  static const char* value(const ::chatbot::FaceTrainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot::FaceTrainResponse> should match 
// service_traits::DataType< ::chatbot::FaceTrain > 
template<>
struct DataType< ::chatbot::FaceTrainResponse>
{
  static const char* value()
  {
    return DataType< ::chatbot::FaceTrain >::value();
  }
  static const char* value(const ::chatbot::FaceTrainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHATBOT_MESSAGE_FACETRAIN_H
