// Generated by gencpp from file r_chatbot/Context.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_CONTEXT_H
#define R_CHATBOT_MESSAGE_CONTEXT_H

#include <ros/service_traits.h>


#include <r_chatbot/ContextRequest.h>
#include <r_chatbot/ContextResponse.h>


namespace r_chatbot
{

struct Context
{

typedef ContextRequest Request;
typedef ContextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Context
} // namespace r_chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r_chatbot::Context > {
  static const char* value()
  {
    return "d4d3081274ba465e7c9b07013f8d6793";
  }

  static const char* value(const ::r_chatbot::Context&) { return value(); }
};

template<>
struct DataType< ::r_chatbot::Context > {
  static const char* value()
  {
    return "r_chatbot/Context";
  }

  static const char* value(const ::r_chatbot::Context&) { return value(); }
};


// service_traits::MD5Sum< ::r_chatbot::ContextRequest> should match 
// service_traits::MD5Sum< ::r_chatbot::Context > 
template<>
struct MD5Sum< ::r_chatbot::ContextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::Context >::value();
  }
  static const char* value(const ::r_chatbot::ContextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::ContextRequest> should match 
// service_traits::DataType< ::r_chatbot::Context > 
template<>
struct DataType< ::r_chatbot::ContextRequest>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::Context >::value();
  }
  static const char* value(const ::r_chatbot::ContextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r_chatbot::ContextResponse> should match 
// service_traits::MD5Sum< ::r_chatbot::Context > 
template<>
struct MD5Sum< ::r_chatbot::ContextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::Context >::value();
  }
  static const char* value(const ::r_chatbot::ContextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::ContextResponse> should match 
// service_traits::DataType< ::r_chatbot::Context > 
template<>
struct DataType< ::r_chatbot::ContextResponse>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::Context >::value();
  }
  static const char* value(const ::r_chatbot::ContextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R_CHATBOT_MESSAGE_CONTEXT_H
