// Generated by gencpp from file r_chatbot/EmotionRecognize.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_EMOTIONRECOGNIZE_H
#define R_CHATBOT_MESSAGE_EMOTIONRECOGNIZE_H

#include <ros/service_traits.h>


#include <r_chatbot/EmotionRecognizeRequest.h>
#include <r_chatbot/EmotionRecognizeResponse.h>


namespace r_chatbot
{

struct EmotionRecognize
{

typedef EmotionRecognizeRequest Request;
typedef EmotionRecognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmotionRecognize
} // namespace r_chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r_chatbot::EmotionRecognize > {
  static const char* value()
  {
    return "6903c14b3c9a61ea8a677558ebfcc4e5";
  }

  static const char* value(const ::r_chatbot::EmotionRecognize&) { return value(); }
};

template<>
struct DataType< ::r_chatbot::EmotionRecognize > {
  static const char* value()
  {
    return "r_chatbot/EmotionRecognize";
  }

  static const char* value(const ::r_chatbot::EmotionRecognize&) { return value(); }
};


// service_traits::MD5Sum< ::r_chatbot::EmotionRecognizeRequest> should match 
// service_traits::MD5Sum< ::r_chatbot::EmotionRecognize > 
template<>
struct MD5Sum< ::r_chatbot::EmotionRecognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::r_chatbot::EmotionRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::EmotionRecognizeRequest> should match 
// service_traits::DataType< ::r_chatbot::EmotionRecognize > 
template<>
struct DataType< ::r_chatbot::EmotionRecognizeRequest>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::r_chatbot::EmotionRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r_chatbot::EmotionRecognizeResponse> should match 
// service_traits::MD5Sum< ::r_chatbot::EmotionRecognize > 
template<>
struct MD5Sum< ::r_chatbot::EmotionRecognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::r_chatbot::EmotionRecognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::EmotionRecognizeResponse> should match 
// service_traits::DataType< ::r_chatbot::EmotionRecognize > 
template<>
struct DataType< ::r_chatbot::EmotionRecognizeResponse>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::EmotionRecognize >::value();
  }
  static const char* value(const ::r_chatbot::EmotionRecognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R_CHATBOT_MESSAGE_EMOTIONRECOGNIZE_H
