// Generated by gencpp from file r_chatbot/FaceRecognizeResponse.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_FACERECOGNIZERESPONSE_H
#define R_CHATBOT_MESSAGE_FACERECOGNIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r_chatbot
{
template <class ContainerAllocator>
struct FaceRecognizeResponse_
{
  typedef FaceRecognizeResponse_<ContainerAllocator> Type;

  FaceRecognizeResponse_()
    : id(0)
    , name()  {
    }
  FaceRecognizeResponse_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FaceRecognizeResponse_

typedef ::r_chatbot::FaceRecognizeResponse_<std::allocator<void> > FaceRecognizeResponse;

typedef boost::shared_ptr< ::r_chatbot::FaceRecognizeResponse > FaceRecognizeResponsePtr;
typedef boost::shared_ptr< ::r_chatbot::FaceRecognizeResponse const> FaceRecognizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r_chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'r_chatbot': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/r_chatbot/msg'], 'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe5a440459dcada9c353c016dfb49d2";
  }

  static const char* value(const ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe5a440459dcadaULL;
  static const uint64_t static_value2 = 0x9c353c016dfb49d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r_chatbot/FaceRecognizeResponse";
  }

  static const char* value(const ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 id\n\
string name\n\
\n\
";
  }

  static const char* value(const ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceRecognizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r_chatbot::FaceRecognizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R_CHATBOT_MESSAGE_FACERECOGNIZERESPONSE_H
