// Generated by gencpp from file r_chatbot/FaceTrainRequest.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_FACETRAINREQUEST_H
#define R_CHATBOT_MESSAGE_FACETRAINREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r_chatbot
{
template <class ContainerAllocator>
struct FaceTrainRequest_
{
  typedef FaceTrainRequest_<ContainerAllocator> Type;

  FaceTrainRequest_()
    : name()
    , devid(0)  {
    }
  FaceTrainRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , devid(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _devid_type;
  _devid_type devid;




  typedef boost::shared_ptr< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceTrainRequest_

typedef ::r_chatbot::FaceTrainRequest_<std::allocator<void> > FaceTrainRequest;

typedef boost::shared_ptr< ::r_chatbot::FaceTrainRequest > FaceTrainRequestPtr;
typedef boost::shared_ptr< ::r_chatbot::FaceTrainRequest const> FaceTrainRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r_chatbot::FaceTrainRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r_chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4deff4fb9e0c005c80be0b13b2cf6ed";
  }

  static const char* value(const ::r_chatbot::FaceTrainRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4deff4fb9e0c005ULL;
  static const uint64_t static_value2 = 0xc80be0b13b2cf6edULL;
};

template<class ContainerAllocator>
struct DataType< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r_chatbot/FaceTrainRequest";
  }

  static const char* value(const ::r_chatbot::FaceTrainRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
string name\n\
int32 devid\n\
\n\
";
  }

  static const char* value(const ::r_chatbot::FaceTrainRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.devid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceTrainRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r_chatbot::FaceTrainRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r_chatbot::FaceTrainRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "devid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.devid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R_CHATBOT_MESSAGE_FACETRAINREQUEST_H
