// Generated by gencpp from file r_chatbot/LoadHistory.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_LOADHISTORY_H
#define R_CHATBOT_MESSAGE_LOADHISTORY_H

#include <ros/service_traits.h>


#include <r_chatbot/LoadHistoryRequest.h>
#include <r_chatbot/LoadHistoryResponse.h>


namespace r_chatbot
{

struct LoadHistory
{

typedef LoadHistoryRequest Request;
typedef LoadHistoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadHistory
} // namespace r_chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r_chatbot::LoadHistory > {
  static const char* value()
  {
    return "fa3ccd00a43e07e133259b77ca345a97";
  }

  static const char* value(const ::r_chatbot::LoadHistory&) { return value(); }
};

template<>
struct DataType< ::r_chatbot::LoadHistory > {
  static const char* value()
  {
    return "r_chatbot/LoadHistory";
  }

  static const char* value(const ::r_chatbot::LoadHistory&) { return value(); }
};


// service_traits::MD5Sum< ::r_chatbot::LoadHistoryRequest> should match 
// service_traits::MD5Sum< ::r_chatbot::LoadHistory > 
template<>
struct MD5Sum< ::r_chatbot::LoadHistoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::LoadHistory >::value();
  }
  static const char* value(const ::r_chatbot::LoadHistoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::LoadHistoryRequest> should match 
// service_traits::DataType< ::r_chatbot::LoadHistory > 
template<>
struct DataType< ::r_chatbot::LoadHistoryRequest>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::LoadHistory >::value();
  }
  static const char* value(const ::r_chatbot::LoadHistoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r_chatbot::LoadHistoryResponse> should match 
// service_traits::MD5Sum< ::r_chatbot::LoadHistory > 
template<>
struct MD5Sum< ::r_chatbot::LoadHistoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::LoadHistory >::value();
  }
  static const char* value(const ::r_chatbot::LoadHistoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::LoadHistoryResponse> should match 
// service_traits::DataType< ::r_chatbot::LoadHistory > 
template<>
struct DataType< ::r_chatbot::LoadHistoryResponse>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::LoadHistory >::value();
  }
  static const char* value(const ::r_chatbot::LoadHistoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R_CHATBOT_MESSAGE_LOADHISTORY_H
