// Generated by gencpp from file r_chatbot/StringList.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_STRINGLIST_H
#define R_CHATBOT_MESSAGE_STRINGLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r_chatbot
{
template <class ContainerAllocator>
struct StringList_
{
  typedef StringList_<ContainerAllocator> Type;

  StringList_()
    : stringlist()  {
    }
  StringList_(const ContainerAllocator& _alloc)
    : stringlist(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _stringlist_type;
  _stringlist_type stringlist;




  typedef boost::shared_ptr< ::r_chatbot::StringList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r_chatbot::StringList_<ContainerAllocator> const> ConstPtr;

}; // struct StringList_

typedef ::r_chatbot::StringList_<std::allocator<void> > StringList;

typedef boost::shared_ptr< ::r_chatbot::StringList > StringListPtr;
typedef boost::shared_ptr< ::r_chatbot::StringList const> StringListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r_chatbot::StringList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r_chatbot::StringList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r_chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'r_chatbot': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/r_chatbot/msg'], 'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::StringList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r_chatbot::StringList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::StringList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r_chatbot::StringList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::StringList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r_chatbot::StringList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r_chatbot::StringList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a7f5c3a3a4d5ed6a386d96d41c2e3aa";
  }

  static const char* value(const ::r_chatbot::StringList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a7f5c3a3a4d5ed6ULL;
  static const uint64_t static_value2 = 0xa386d96d41c2e3aaULL;
};

template<class ContainerAllocator>
struct DataType< ::r_chatbot::StringList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r_chatbot/StringList";
  }

  static const char* value(const ::r_chatbot::StringList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r_chatbot::StringList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] stringlist\n\
";
  }

  static const char* value(const ::r_chatbot::StringList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r_chatbot::StringList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stringlist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r_chatbot::StringList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r_chatbot::StringList_<ContainerAllocator>& v)
  {
    s << indent << "stringlist[]" << std::endl;
    for (size_t i = 0; i < v.stringlist.size(); ++i)
    {
      s << indent << "  stringlist[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.stringlist[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // R_CHATBOT_MESSAGE_STRINGLIST_H
