// Generated by gencpp from file r_chatbot/WriteHistory.msg
// DO NOT EDIT!


#ifndef R_CHATBOT_MESSAGE_WRITEHISTORY_H
#define R_CHATBOT_MESSAGE_WRITEHISTORY_H

#include <ros/service_traits.h>


#include <r_chatbot/WriteHistoryRequest.h>
#include <r_chatbot/WriteHistoryResponse.h>


namespace r_chatbot
{

struct WriteHistory
{

typedef WriteHistoryRequest Request;
typedef WriteHistoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteHistory
} // namespace r_chatbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r_chatbot::WriteHistory > {
  static const char* value()
  {
    return "fa3ccd00a43e07e133259b77ca345a97";
  }

  static const char* value(const ::r_chatbot::WriteHistory&) { return value(); }
};

template<>
struct DataType< ::r_chatbot::WriteHistory > {
  static const char* value()
  {
    return "r_chatbot/WriteHistory";
  }

  static const char* value(const ::r_chatbot::WriteHistory&) { return value(); }
};


// service_traits::MD5Sum< ::r_chatbot::WriteHistoryRequest> should match 
// service_traits::MD5Sum< ::r_chatbot::WriteHistory > 
template<>
struct MD5Sum< ::r_chatbot::WriteHistoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::WriteHistory >::value();
  }
  static const char* value(const ::r_chatbot::WriteHistoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::WriteHistoryRequest> should match 
// service_traits::DataType< ::r_chatbot::WriteHistory > 
template<>
struct DataType< ::r_chatbot::WriteHistoryRequest>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::WriteHistory >::value();
  }
  static const char* value(const ::r_chatbot::WriteHistoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r_chatbot::WriteHistoryResponse> should match 
// service_traits::MD5Sum< ::r_chatbot::WriteHistory > 
template<>
struct MD5Sum< ::r_chatbot::WriteHistoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r_chatbot::WriteHistory >::value();
  }
  static const char* value(const ::r_chatbot::WriteHistoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r_chatbot::WriteHistoryResponse> should match 
// service_traits::DataType< ::r_chatbot::WriteHistory > 
template<>
struct DataType< ::r_chatbot::WriteHistoryResponse>
{
  static const char* value()
  {
    return DataType< ::r_chatbot::WriteHistory >::value();
  }
  static const char* value(const ::r_chatbot::WriteHistoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R_CHATBOT_MESSAGE_WRITEHISTORY_H
