// Generated by gencpp from file chatbot/FaceRecognizeRequest.msg
// DO NOT EDIT!


#ifndef CHATBOT_MESSAGE_FACERECOGNIZEREQUEST_H
#define CHATBOT_MESSAGE_FACERECOGNIZEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chatbot
{
template <class ContainerAllocator>
struct FaceRecognizeRequest_
{
  typedef FaceRecognizeRequest_<ContainerAllocator> Type;

  FaceRecognizeRequest_()
    : devid(0)  {
    }
  FaceRecognizeRequest_(const ContainerAllocator& _alloc)
    : devid(0)  {
  (void)_alloc;
    }



   typedef int32_t _devid_type;
  _devid_type devid;




  typedef boost::shared_ptr< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceRecognizeRequest_

typedef ::chatbot::FaceRecognizeRequest_<std::allocator<void> > FaceRecognizeRequest;

typedef boost::shared_ptr< ::chatbot::FaceRecognizeRequest > FaceRecognizeRequestPtr;
typedef boost::shared_ptr< ::chatbot::FaceRecognizeRequest const> FaceRecognizeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chatbot::FaceRecognizeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chatbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/media/sf_GitHub/Perception_Robotics/catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "899fc876fe79c419f24f892812c17e47";
  }

  static const char* value(const ::chatbot::FaceRecognizeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x899fc876fe79c419ULL;
  static const uint64_t static_value2 = 0xf24f892812c17e47ULL;
};

template<class ContainerAllocator>
struct DataType< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chatbot/FaceRecognizeRequest";
  }

  static const char* value(const ::chatbot::FaceRecognizeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int32 devid\n\
\n\
";
  }

  static const char* value(const ::chatbot::FaceRecognizeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.devid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceRecognizeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chatbot::FaceRecognizeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chatbot::FaceRecognizeRequest_<ContainerAllocator>& v)
  {
    s << indent << "devid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.devid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHATBOT_MESSAGE_FACERECOGNIZEREQUEST_H
